# Generated by Django 3.2.5 on 2021-09-02 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='datetime',
        ),
    ]
