# Generated by Django 3.2.5 on 2021-09-02 20:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_customer_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='datetime',
            name='_endtime',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
