# Generated by Django 3.2.6 on 2021-08-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210824_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='services',
            field=models.ManyToManyField(to='core.Service'),
        ),
    ]
