# Generated by Django 3.2.6 on 2021-08-24 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_professional_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='employees',
            field=models.ManyToManyField(blank=True, null=True, to='core.Employee'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='services',
            field=models.ManyToManyField(blank=True, null=True, to='core.Service'),
        ),
    ]
