# Generated by Django 3.2.5 on 2021-09-02 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_datetime__endtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datetime',
            name='_endtime',
        ),
    ]
