# Generated by Django 3.2.5 on 2021-09-09 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_datetime__endtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_customer', to='core.customer'),
        ),
    ]
