# Generated by Django 3.2.5 on 2021-09-09 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
        ('core', '0006_auto_20210909_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenant.tenant'),
        ),
        migrations.AlterField(
            model_name='datetime',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenant.tenant'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenant.tenant'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenant.tenant'),
        ),
        migrations.AlterField(
            model_name='service',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenant.tenant'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenant.tenant'),
        ),
    ]
