# Generated by Django 3.2.5 on 2021-08-24 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210824_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='services',
        ),
        migrations.RemoveField(
            model_name='professional',
            name='services',
        ),
        migrations.AddField(
            model_name='service',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.user'),
            preserve_default=False,
        ),
    ]
