# Generated by Django 3.2.5 on 2021-08-25 00:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210824_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='services',
            field=models.ManyToManyField(related_name='user_employee', to='core.Service'),
        ),
        migrations.AlterField(
            model_name='business',
            name='employees',
            field=models.ManyToManyField(blank=True, related_name='employee_business', to='core.Employee'),
        ),
        migrations.AlterField(
            model_name='service',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
